services:
  code-1:
    image: ce-learning/code:latest
    build:
      context: .
      dockerfile: ./deployments/code/Dockerfile
    ports:
      - 9980:9980
    restart: always
    volumes:
      - ./deployments/code/scripts:/opt/collaboraoffice/share/Scripts/python
    environment:
      aliasgroup1: http://host.docker.internal:5001
      username: admin
      password: zaQ@123456!
      extra_params: --o:ssl.enable=false --o:security.enable_macros_execution=true --o:security.macro_security_level=1
    networks:
      - cel-bridge

networks:
  cel-bridge:
    driver: bridge
